// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class AccountType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int? DurationInDays { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<UserAccountSubscription> UserAccountSubscriptions { get; set; } = new List<UserAccountSubscription>();
}