// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class AuditReport
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Model { get; set; }

    public string Url { get; set; }

    public int OverallScore { get; set; }

    public int CriticalIssue { get; set; }

    public int Warning { get; set; }

    public int Opportunity { get; set; }

    public string PassedCheck { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Element> Elements { get; set; } = new List<Element>();

    public virtual User User { get; set; }
}