// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class AuditReport
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Url { get; set; }

    public int OverallScore { get; set; }

    public string CriticalIssue { get; set; }

    public string Warning { get; set; }

    public string Opportunity { get; set; }

    public string PassedCheck { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}