// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class ContentOptimization
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Keyword { get; set; }

    public string OriginalContent { get; set; }

    public string ContentLenght { get; set; }

    public int OptimizationLevel { get; set; }

    public string ReadabilityLevel { get; set; }

    public bool? IncludeCitation { get; set; }

    public string OptimizedContent { get; set; }

    public int? Seoscore { get; set; }

    public int? Readability { get; set; }

    public int? Engagement { get; set; }

    public int? Originality { get; set; }

    public DateTime? CreatedAt { get; set; }
}