// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class Element
{
    public int Id { get; set; }

    public string Url { get; set; }

    public string Element1 { get; set; }

    public string CurrentValue { get; set; }

    public string Status { get; set; }

    public int Important { get; set; }
}