// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class Keyword
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string SearchKeyword { get; set; }

    public string Keyword1 { get; set; }

    public int SearchVolume { get; set; }

    public int Difficulty { get; set; }

    public decimal Cpc { get; set; }

    public string Competition { get; set; }

    public string Intent { get; set; }

    public string Trend { get; set; }

    public virtual User User { get; set; }
}