// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class RankTracking
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Keyword { get; set; }

    public int? Rank { get; set; }
}