// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class SEOBoostAIContext : DbContext
{
    public SEOBoostAIContext()
    {
    }

    public SEOBoostAIContext(DbContextOptions<SEOBoostAIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditReport> AuditReports { get; set; }

    public virtual DbSet<ContentOptimization> ContentOptimizations { get; set; }

    public virtual DbSet<Element> Elements { get; set; }

    public virtual DbSet<Keyword> Keywords { get; set; }

    public virtual DbSet<RankTracking> RankTrackings { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);


//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=HANAYUKI\\SQLEXPRESS;Initial Catalog=SEOBoostAI;Persist Security Info=True;User ID=HANAYUKI;Password=123456;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditReport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AuditRep__3214EC27A0DC36C6");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CriticalIssue)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Opportunity)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PassedCheck)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Warning)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.AuditReports)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AuditRepo__UserI__5535A963");
        });

        modelBuilder.Entity<ContentOptimization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentO__3214EC279A637341");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ContentLenght)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IncludeCitation).HasDefaultValue(true);
            entity.Property(e => e.Keyword)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.OriginalContent).IsRequired();
            entity.Property(e => e.ReadabilityLevel)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Seoscore).HasColumnName("SEOScore");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.ContentOptimizations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ContentOp__UserI__5AEE82B9");
        });

        modelBuilder.Entity<Element>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Elements__3214EC2747A565E8");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CurrentValue)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Element1)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Element");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Keyword>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Keywords__3214EC27F812BA61");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Competition)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Cpc)
                .HasColumnType("money")
                .HasColumnName("CPC");
            entity.Property(e => e.Intent)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Keyword1)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Keyword");
            entity.Property(e => e.SearchKeyword).HasMaxLength(100);
            entity.Property(e => e.Trend)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Keywords)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Keywords__UserID__4F7CD00D");
        });

        modelBuilder.Entity<RankTracking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RankTrac__3214EC2787FA85BC");

            entity.ToTable("RankTracking");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Keyword).HasMaxLength(100);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.RankTrackings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RankTrack__UserI__52593CB8");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC276EA14300");

            entity.HasIndex(e => e.Username, "UQ__Users__536C85E483BFA6B6").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AccountType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("user");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}