// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public int WalletId { get; set; }

    public decimal Money { get; set; }

    public string Description { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public string BankTransId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Wallet Wallet { get; set; }
}