// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class UserFeaturePurchase
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int FeatureId { get; set; }

    public DateTime PurchaseDate { get; set; }

    public bool IsUsed { get; set; }

    public virtual Feature Feature { get; set; }

    public virtual User User { get; set; }
}