// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class UserAccountSubscription
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int AccountTypeId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool IsActive { get; set; }

    public virtual AccountType AccountType { get; set; }

    public virtual User User { get; set; }
}