// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEOBoostAI.Repository.Models;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Role { get; set; }

    public string Avatar { get; set; }

    public string AccountType { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AuditReport> AuditReports { get; set; } = new List<AuditReport>();

    public virtual ICollection<ContentOptimization> ContentOptimizations { get; set; } = new List<ContentOptimization>();

    public virtual ICollection<Keyword> Keywords { get; set; } = new List<Keyword>();

    public virtual ICollection<RankTracking> RankTrackings { get; set; } = new List<RankTracking>();
}